.code
extern mProcs:QWORD
D3DAssemble_wrapper proc
	jmp mProcs[0*8]
D3DAssemble_wrapper endp
D3DCompile_wrapper proc
	jmp mProcs[1*8]
D3DCompile_wrapper endp
D3DCompile2_wrapper proc
	jmp mProcs[2*8]
D3DCompile2_wrapper endp
D3DCompileFromFile_wrapper proc
	jmp mProcs[3*8]
D3DCompileFromFile_wrapper endp
D3DCompressShaders_wrapper proc
	jmp mProcs[4*8]
D3DCompressShaders_wrapper endp
D3DCreateBlob_wrapper proc
	jmp mProcs[5*8]
D3DCreateBlob_wrapper endp
D3DCreateFunctionLinkingGraph_wrapper proc
	jmp mProcs[6*8]
D3DCreateFunctionLinkingGraph_wrapper endp
D3DCreateLinker_wrapper proc
	jmp mProcs[7*8]
D3DCreateLinker_wrapper endp
D3DDecompressShaders_wrapper proc
	jmp mProcs[8*8]
D3DDecompressShaders_wrapper endp
D3DDisassemble_wrapper proc
	jmp mProcs[9*8]
D3DDisassemble_wrapper endp
D3DDisassemble10Effect_wrapper proc
	jmp mProcs[10*8]
D3DDisassemble10Effect_wrapper endp
D3DDisassemble11Trace_wrapper proc
	jmp mProcs[11*8]
D3DDisassemble11Trace_wrapper endp
D3DDisassembleRegion_wrapper proc
	jmp mProcs[12*8]
D3DDisassembleRegion_wrapper endp
D3DGetBlobPart_wrapper proc
	jmp mProcs[13*8]
D3DGetBlobPart_wrapper endp
D3DGetDebugInfo_wrapper proc
	jmp mProcs[14*8]
D3DGetDebugInfo_wrapper endp
D3DGetInputAndOutputSignatureBlob_wrapper proc
	jmp mProcs[15*8]
D3DGetInputAndOutputSignatureBlob_wrapper endp
D3DGetInputSignatureBlob_wrapper proc
	jmp mProcs[16*8]
D3DGetInputSignatureBlob_wrapper endp
D3DGetOutputSignatureBlob_wrapper proc
	jmp mProcs[17*8]
D3DGetOutputSignatureBlob_wrapper endp
D3DGetTraceInstructionOffsets_wrapper proc
	jmp mProcs[18*8]
D3DGetTraceInstructionOffsets_wrapper endp
D3DLoadModule_wrapper proc
	jmp mProcs[19*8]
D3DLoadModule_wrapper endp
D3DPreprocess_wrapper proc
	jmp mProcs[20*8]
D3DPreprocess_wrapper endp
D3DReadFileToBlob_wrapper proc
	jmp mProcs[21*8]
D3DReadFileToBlob_wrapper endp
D3DReflect_wrapper proc
	jmp mProcs[22*8]
D3DReflect_wrapper endp
D3DReflectLibrary_wrapper proc
	jmp mProcs[23*8]
D3DReflectLibrary_wrapper endp
D3DReturnFailure1_wrapper proc
	jmp mProcs[24*8]
D3DReturnFailure1_wrapper endp
D3DSetBlobPart_wrapper proc
	jmp mProcs[25*8]
D3DSetBlobPart_wrapper endp
D3DStripShader_wrapper proc
	jmp mProcs[26*8]
D3DStripShader_wrapper endp
D3DWriteBlobToFile_wrapper proc
	jmp mProcs[27*8]
D3DWriteBlobToFile_wrapper endp
DebugSetMute_wrapper proc
	jmp mProcs[28*8]
DebugSetMute_wrapper endp
end
